name: Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.3
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: Sprinkles/package-lock.json

    - name: Fetch external dependencies
      run: ./fetch_external_deps.bat
    
    - name: Build Natives
      run: |
        vcpkg install --triplet x86-windows-static-md
        vcpkg integrate install
        msbuild /p:Configuration=Release
    
    - name: Build TypeScript
      run: |
        cd Sprinkles/
        npm install
        npm run build
        Copy-Item dist/bundle.js ../build/Release/Soggfy.js
        Copy-Item dist/bundle.js.map ../build/Release/Soggfy.js.map
        cd ../
        
    - name: Create Zip
      run: |
        if ($Env:GITHUB_REF_TYPE -eq "tag") {
          $ver = $Env:GITHUB_REF.Substring(1);
        } else {
          $ver = $Env:GITHUB_SHA.Substring(0, 8) + "-pre";
        }
        echo $ver
        Rename-Item -Path ./build/Release -NewName Soggfy-$ver
        7z a "-xr!*.lib" "-xr!*.exp" "-xr!*.pdb" build/Soggfy-$ver.zip ./build/Soggfy-$ver

    - name: Upload Binaries
      uses: softprops/action-gh-release@v1
      if: ${{ github.ref_type == 'tag' }}
      with:
        draft: false
        prerelease: ${{ contains(env.GITHUB_REF, '-pre') }}
        files: 'build/*.zip'
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      if: ${{ github.ref_type != 'tag' }}
      with:
        path: build/*.zip